name: firebase_credentials_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  flutter_icons: ^0.3.1
  
  provider: ^3.1.0+1 
  get_it: ^3.0.3

  cloud_firestore: ^0.12.9+5
  firebase_auth: ^0.14.0+2
  firebase_core: ^0.4.0+8

  loading_animations: "^2.0.0"


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

